config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations"
  }
  get 'static_pages/contact'

  get 'static_pages/faq'

  get 'static_pages/tips'

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ interests: [] }, :major, :name,
  		:email, :password, :password_confirmation) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ interests: [] }, :major, :name, :email,
  		:password, :password_confirmation, :current_password ) }
  end

  def after_sign_in_path_for(resource)
  	 edit_user_registration_path
  end

  # def after_update_path_for(resource)
  # 	 edit_user_registration_path
  # end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


	def create
		build_resource(sign_up_params)

		resource_saved = resource.save
		yield resource if block_given?
		if resource_saved
			@name = resource.name
			if resource.active_for_authentication?
				set_flash_message :notice, :signed_up if is_flashing_format?
				sign_up(resource_name, resource)
				respond_with resource, location: after_sign_up_path_for(resource)
			else
				set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
				expire_data_after_sign_in!
				respond_with resource, location: after_inactive_sign_up_path_for(resource)
			end
		else
			clean_up_passwords resource
			messages = resource.errors.full_messages.map { |msg| "<li>#{msg}</li>" }.join
			sentence = "We cannot create your account because of " + ActionController::Base.helpers.pluralize(resource.errors.count, "error")

			html = <<-HTML
			<div id="custom_error">
				<h5>#{sentence}</h5>
				<ul>#{messages}</ul>
			</div>
			HTML
			redirect_to root_path(error_message: html.html_safe)
		end
	end

	protected

	def after_update_path_for(resource)
		edit_user_registration_path
	end

	# def after_inactive_sign_up_path_for(resource)
	# 	edit_user_registration_path
	# end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	puts params
  	if params[:error_message] != nil
  		puts "YAYAAYYAAY"
  		flash[:alert] = params[:error_message].html_safe
  	end
  end

  def contact
  end

  def faq
  end

  def tips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>    
    </div>
    <div class="navbar-brand">
      <%= link_to image_tag("final_logo.png", id: "logo"), root_path, "data-no-turbolink" => true %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
       <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
       <% else %>
       <li><%= link_to "Sign in", new_user_session_path %></li>
       <% end %>
       <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "My profile", edit_user_registration_path %></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
	<html>
	<head>
		<title>Serendipity</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag 'logo_only.png' %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Serendipity is a platform for cal students to foster relationships with others the would not have met.">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<!-- below 1200 -->
		<div id="desktopTest" class="hidden-md"></div>
		<!-- below 992 -->
		<div id="desktopTest2" class="hidden-sm"></div>
		<!-- below 768 -->
		<div id="desktopTest3" class="hidden-xs"></div>
		<% if flash[:notice] != nil %>
		<div class="notification-notice"> 
			<span class="x-alert"> x </span>
			<p class="notice"><%= flash[:notice] %></p>
		</div>
		<% end %>
		<% if flash[:alert] != nil %>
		<div class="notification-alert"> 
			<span class="x-alert"> x </span>
			<p class="alert"><%= flash[:alert] %></p>
		</div>
		<% end %>
		<%= yield %>
	</body>
	</html>

app/views/static_pages/_signup_page.html.erb
<div class="container-fluid">
<h2 id="signup-header">Sign up</h2>

	<div class="row">

	<div class="col-xs-6 col-sm-5 col-sm-offset-1">
		<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
		  <%= devise_error_messages! %>

		  <div><%= f.label :name %><br />
		  <%= f.text_field :name %></div>

		  <div><%= f.label :email %><br />
		  <%= f.email_field :email%></div>

		  <div><%= f.label "major/s" %><br />
		  <%= f.text_field :major %></div>

		  <div><%= f.label :password %><br />
		    <%= f.password_field :password, autocomplete: "off" %></div>

		  <div><%= f.label :password_confirmation %><br />
		    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  	</div>

	<div class="col-xs-6 col-sm-5">

		<div class="interest_holder">
	  	<div><%= f.label :interests %><br />
			  <input class="interest" name="user[interests][]" type="text">
			  <input class="interest" name="user[interests][]" type="text">
			  <input class="interest" name="user[interests][]" type="text">
			</div>
		</div>
		<span class="add_interests">+ Add interest</span>

  	<div><%= f.submit "Sign up", class: "btn" %></div>
		<% end %>
		<%= render "devise/shared/links", home: true %>

	</div>

	</div>

</div>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/faq.html.erb
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/home.html.erb
<div id="fullpage" data-no-turbolink>
	<div id="first" class="table-custom section active">
		<div class="vertical-align">
			<%= image_tag("logo_only.png", id: "logo_homepage") %>
			<div id="tagline_homepage">Foster relationships with a fellow CAL student you may have otherwise not met.</div>
		</div>
	</div>
	<div id="second" class="section">
		<div id="homeblock-holder">
			<div class="container-fluid">
				<div class="row">
					<div id="homeblock1" class="col-xs-12 col-lg-6 homeblock blue-bg table-custom">
						<div class="home-steps-title tc-vert-center white">
							<span>Meet someone new</span>
						</div>
					</div>
					<div id="homeblock4" class="col-xs-12 col-lg-6 homeblock gold-bg table-custom">
						<div class="home-steps-title tc-vert-center blue">
							<span>Foster</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div id="homeblock2" class="col-xs-12 col-lg-6 homeblock gold-bg table-custom">
						<div class="home-steps-title tc-vert-center blue">
							<span>Real talk</span>
						</div>
					</div>
					<div id="homeblock3" class="col-xs-12 col-lg-6 homeblock blue-bg table-custom">
						<div class="home-steps-title tc-vert-center white">
							<span>Reflect</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% if !user_signed_in? %>
		<div id="third" class="section">
			<%= render "signup_page" %>
		</div>
	<% end %>
</div>

app/views/static_pages/tips.html.erb
<h1>StaticPages#tips</h1>
<p>Find me in app/views/static_pages/tips.html.erb</p>